### ISSUE TITLE
缺少文件MyTrainer.py

### ISSUE THREAD

**Issue by variationalkk** [wdkwdkwdk/CLONE_DK#5]
https://github.com/wdkwdkwdk/CLONE_DK/blob/534a114836f2c45b5d51649fbe98c284dbbf6d8f/finetune.py#L7

**Comment by wdkwdkwdk** [comment]
> 参考我提到的 https://github.com/yuanzhoulvpi2017/zero_nlp/tree/main/simple_thu_chatglm6b

**Comment by variationalkk** [comment]
好的，多谢。
